weather_forecast:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID', 'ibague-weather') }}"
      dataset: "{{ env_var('GCP_DATASET', 'weather_data') }}"
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
  
  target: dev
